### ISSUE TITLE
Not display short URL on /url

### ISSUE THREAD

**Issue by seihello** [EduardoEduBox/NodeMidTerm#11]
The requirement says there should be short URL instead of number

![Screenshot 2023-09-17 at 9 10 04 PM](https://github.com/EduardoEduBox/NodeMidTerm/assets/34885995/252ca002-3310-452a-ae21-7ab5d50e2d19)

**Comment by seihello** [comment]
![Screenshot 2023-09-17 at 9 10 04 PM](https://github.com/EduardoEduBox/NodeMidTerm/assets/34885995/1c4a64e3-377d-4b5a-bf1d-d4b2e9547bb1)

**Comment by EduardoEduBox** [comment]
now when the user do not put any tinylinks, it is gonna show the id, otherwise it is gonna show all the tinyUrl that the user made!

FIXED!
