### ISSUE TITLE
Not redirect to /urls or /login from /

### ISSUE THREAD

**Issue by seihello** [EduardoEduBox/NodeMidTerm#13]
You created the home page for us, but actually the requirement says it should jump to /urls or /login

<img width="326" alt="Screenshot 2023-09-17 at 9 18 00 PM" src="https://github.com/EduardoEduBox/NodeMidTerm/assets/34885995/a880f439-0e25-4c72-86ab-86c1fbde968d">

**Comment by EduardoEduBox** [comment]
you made so if the user is not logged in, the home page is gonna show up with the login button and register button, so this problem is now obsolete 

FIXED!
